hanaro4-dIA/dia_pb_fe

public/data/Consultings.json
src/components/PbCalendar.tsx

> #30
> 모달 외부 영역 클릭시 창 닫기
모달 내부 요소 시간 오름차순 정렬 
모달 내부 텍스트 위치 수정 
destructuring

[fix : PbCalendar] : PbCalendarModal 수정

---

public/data/Consultings.json
src/components/ConsultationRequest.tsx
src/components/ScheduledConsultationList.tsx

> #36 
> 요청된 상담 컴포넌트 - 요청된 날짜에 따른 오름차순 정렬
> 예정된 상담 컴포넌트 - 예정된 빠른 날짜에 따른 오름차순 정렬

[feat] : 상담 요청 컴포넌트와 예정된 상담 일정 컴포넌트에 날짜 오름차순 정렬 추가

---

src/pages/DictionaryPage.tsx

[fix] : 딕셔너리 페이지 높이 수정

---

public/data/Consultings.json
src/components/ConsultationJournalList.tsx
src/components/ReadJournal.tsx
src/pages/DictionaryPage.tsx

> #49 
상담일지 자세히 보기 모달창-> 새창으로 수정
딕셔너리 밑줄 추가

상담일지 자세히 보기 모달창-> 새창으로 수정

---

src/pages/DictionaryPage.tsx

[feat] : a태그에 색상 및 밑줄 추가

---

src/components/PbProfile.tsx

[style:profile] : bio 크기 수정

---

public/data/Journals.json
public/data/PB.json
src/components/ConsultationJournalList.tsx
src/components/ReadJournal.tsx
src/lib/types.ts

> #54 
Journals.json 수정
PB.json 수정
상담일지리스트 컴포넌트 수정
상담일지자세히보기 컴포넌트 수정
상담일지 pb 이름 연결 수정

[feat] : Journals.json을 수정하여 상담사가 이전의 상담사(박수종 상담사)가 상담한 내용을 볼 수 있게 추가

---

src/App.tsx
src/components/ConsultationJournalList.tsx
src/components/CustomerInformation.tsx
src/components/GuestList.tsx
src/components/ScheduledConsultationList.tsx
src/pages/ConsultingPage.tsx
src/pages/CustomerDetailPage.tsx
src/pages/DictionaryPage.tsx
src/pages/MainPage.tsx

> #58 
> any, 중복되는 타입 삭제
types 파일에 있는 타입 import하여 사용
타입 선언 형식 맞추기 (T~props)

[docs] : any, null 중복되는 type에 대해서 수정

---

src/components/PbProfile.tsx

> Pb프로필에서 태그 between으로 넘어가는거 수정

[fix] : 태그 between 현상 수정

---

src/components/CustomerInformation.tsx

> #79 
CustomerInformation.tsx에 arrowDrop 추가하였음

[feat] : 손님 정보 페이지 arrowDrop 추가

---

src/components/ConsultationJournalList.tsx
src/components/GuestList.tsx
src/components/NotiHistory.tsx
src/components/SearchField.tsx
src/pages/DictionaryPage.tsx

> #72
> 상담일지 리스트 영역 내 상담일지 제목, 내용에 대한 검색 기능 추가
> 검색창 컴포넌트 따로 빼서 재사용

상담일지 리스트 영역 내 검색기능 추가

---

src/App.tsx
src/components/NotiHistory.tsx
src/components/WriteNoti.tsx
src/pages/NotificationPage.tsx

> 새로운 쪽지 전송하기 WriteNoi 컴포넌트 생성
> NotiHistory 가로길이 조정 및 스크롤 시 검색영역 고정 등 디자인 수정

notificationPage 생성

---

pnpm-lock.yaml
src/components/MakeJournal.tsx

> #72 
> MakeJournal 메타데이터 수정, 상담스크립트 작성란 삭제

[feat] : MakeJournal 자세히 보기 수정

---

src/components/NotiHistory.tsx

[fix] NotiHistory 길이 고정

---

src/containers/ConsultationRequest.tsx

ConsultationRequest에서 모든 상담 요청이 승인 되었을 경우의 테두리 수정

---

src/components/NavigationBtn.tsx

네비게이션 버튼에 마우스 올렸을 시, 어떤 버튼인지 타이틀 추가

---

src/containers/PbCalendar.tsx

> #126 
> ![image](https://github.com/user-attachments/assets/e581d3b0-f025-44c9-b716-f9c28097654f)
> pb캘린더의 z-20 추가

[fix] : PbCalendar의 z-Index 수정

---

src/containers/ConsultationScript.tsx
src/containers/MakeJournal.tsx
src/containers/Stt.tsx
src/pages/ConsultingPage.tsx

> #142 
> STT 컴포넌트의 섹션 타이틀 ‘상담 스크립트’로 변경
> 키워드 추출용 버튼 '적용'으로 변경
> MakeJournal 컴포넌트 내 textarea 간 간격 조정

Feature/change consulting page UI

---

src/containers/NotificationHistory.tsx
src/pages/NotificationDetailsWindow.tsx
src/types/dataTypes.ts

> #157
> #158 
> #160 
GET - 이전에 전송한 쪽지 리스트 조회 
GET - 쪽지 자세히 보기
GET - 특정 손님에게 보낸 쪽지 조회
에 대한 GET api 연결을 하였습니다.

[feat] : pb/notifications에 대한 GET api 추가 (3개)

---

src/containers/MakeJournal.tsx
src/pages/RequestContentPage.tsx

> #176 
> 상담 일지를 작성할때, 요청 내용을 자세히 볼 수 있게 하였습니다!

[feat] : 요청 내용 자세히보기 api 연결

---

src/containers/PbCalendar.tsx

> #152 #165 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

[feat] : calendar 전체 일정 조회, 특정 날짜 일정 조회 api 연결

---

src/containers/PbProfile.tsx

> #174 
> PB프로필이 변경 가능
하지만 커스텀훅을 사용해서 리팩토링 해야함

Feature/pb/profile (태그, 한줄소개, 프로필 수정 가능)

---

src/containers/WriteNotification.tsx

> .env파일 수정으로 인해서 api의 연결부분의 url 수정했습니다
+ 오류도 useEffect로 수정해서 넣었습니다!

[fix] : 쪽지 전송 관련, url 수정

---

src/containers/PbCalendar.tsx

> #198 
> 캘린더에서 사용하는 전체 일정 조회 api 수정

[fix] 캘린더 api 수정

---

src/components/JournalProductInputArea.tsx
src/containers/MakeJournal.tsx
src/pages/RequestContentPage.tsx

> #181 #196 
> 상담 일지 전송 기능 연결 - 완료
> 상담 일지 임시 저장 기능 - 완료
> 상담 일지 임시 저장 불러오기 기능 - 완료

[feat] : 상담 일지 전송 기능 연결

---

src/containers/MakeJournal.tsx

[fix] : MakeJournal 수정

---

src/containers/ConsultationScript.tsx

> #200 
> script 높이 자동 조절 및 text 변경 가능하게 작업했씁니다

[fix] : script 높이 자동 조절 및 text 변경 가능하게 작업

---

src/containers/ConsultationScript.tsx

> #193 
> front와 server put api 연결, server에서 명시한 request형식으로 scripts데이터 변환하기

[feat] : put api 연결 - 스크립트 수정

---

src/containers/RequestedConsultationsList.tsx

[feat] : 들어온 상담 요청 웹소켓 연결

---

src/containers/ConsultationScript.tsx

> #이슈번호
> 스크립트 안에 말풍선 삭제 시 바로 반영되도록 수정
filter 사용함
> 말풍선 옆 삭제 버튼 위치 수정

[fix] : 스크립트 delete 한 것이 바로 반영되도록 filter 사용

---

src/components/ConsultationJournalListItem.tsx
src/types/dataTypes.ts

> #215 
> 상담일지가 완료가 되지 않은 일지들도 보이는 문제가 있었습니다.
완료된 상담일지만 보이게끔 if를 넣어서 처리했습니다.
데이터타입도 추가했습니다!

[feat] : 상담일지가 complete:true만 보이게끔 추가

---

src/containers/PbProfile.tsx
src/containers/RequestedConsultationsList.tsx

> #221 
> PB availability api 연결
웹소켓 url 수정

[feat] : put/availability 연결

---

src/containers/MakeJournal.tsx

> #이슈번호
> makejournal 컴포넌트 websocket

[feat] : journalkeyword websocket
